// Export all pages
export * from './Auth';
export * from './Admin';
export * from './Staff';
export * from './Head';
export * from './Lecturer';
export * from './Student';
export * from './Projects';
export * from './Groups';
export * from './Collaboration';
export * from './Profile';
export * from './AI';
