name: "Bug report"
description: "Report a reproducible problem"
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: What you expected vs what happened.
      placeholder: "Steps + observed behavior"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: "1) ... 2) ... 3) ..."
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: "OS, browser (if frontend), python/node versions"
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste logs (remove secrets) or add screenshots.
